# One politician per spectrum per election, 1990–2026. Fields:
# (election, spectrum, name, party, bio_en, bio_pt, why_en, why_pt)
# Bios are deliberately short (3–5 lines). Where the spectrum had no seats that year, the
# card says so and uses the party's leader or presidential candidate.

P = [
# ───────────────────────── 1990 ─────────────────────────
(1990,"far_right","Enéas Carneiro","PRONA · RJ",
 "Born 1938, Rio Branco. Physician and cardiologist, with further degrees in mathematics and physics. Founded PRONA in 1989 and ran for president that year with 0.5% of the vote and a 15-second TV slot that made him a national figure. No seats in 1990.",
 "Nascido em 1938, Rio Branco. Médico cardiologista, com formação adicional em matemática e física. Fundou o PRONA em 1989 e disputou a Presidência naquele ano com 0,5% dos votos e 15 segundos de TV que o tornaram figura nacional. Sem cadeiras em 1990.",
 "Why here: the only far-right party with a national presence in 1990; the column is empty.",
 "Por que aqui: o único partido de extrema direita com presença nacional em 1990; a coluna está vazia."),
(1990,"right","Luís Eduardo Magalhães","PFL · BA",
 "Born 1955, Salvador; died 1998. Law degree, Catholic University of Salvador. Son of Antônio Carlos Magalhães, federal deputy from 1987, PFL leader in the Chamber and its president 1995–97, the main articulator of FHC's reforms in Congress. Died of a heart attack at 43.",
 "Nascido em 1955, Salvador; morreu em 1998. Bacharel em Direito pela Universidade Católica do Salvador. Filho de Antônio Carlos Magalhães, deputado federal a partir de 1987, líder do PFL na Câmara e seu presidente em 1995–97, principal articulador das reformas de FHC no Congresso. Morreu de infarto aos 43 anos.",
 "Why here: PFL, heir of the regime's ARENA/PDS, was the largest right-wing bench of the decade.",
 "Por que aqui: o PFL, herdeiro da ARENA/PDS do regime, era a maior bancada de direita da década."),
(1990,"centre_right","Álvaro Valle","PL · RJ",
 "Born 1934, Rio de Janeiro; died 2000. Career diplomat (Rio Branco Institute) and lawyer. Federal deputy from 1971 (ARENA), founded the Liberal Party in 1985 and presided over it until his death; the PL of this era was a small pro-business party before its 2000s turn to evangelical politics.",
 "Nascido em 1934, Rio de Janeiro; morreu em 2000. Diplomata de carreira (Instituto Rio Branco) e advogado. Deputado federal a partir de 1971 (ARENA), fundou o Partido Liberal em 1985 e o presidiu até morrer; o PL dessa época era um pequeno partido pró-empresariado, antes da guinada evangélica dos anos 2000.",
 "Why here: PL and PTB were the market-liberal centre-right of 1990; PSDB was still at the centre.",
 "Por que aqui: PL e PTB eram a centro-direita liberal de 1990; o PSDB ainda estava no centro."),
(1990,"centre","Ibsen Pinheiro","PMDB · RS",
 "Born 1935, Porto Alegre. Law degree, PUC-RS; public prosecutor. Federal deputy from 1983, president of the Chamber 1991–93, where he conducted Collor's impeachment. Lost his mandate in the 1994 budget scandal, was later cleared, and returned to the Chamber in 2007.",
 "Nascido em 1935, Porto Alegre. Bacharel em Direito pela PUC-RS; promotor de Justiça. Deputado federal a partir de 1983, presidente da Câmara em 1991–93, quando conduziu o impeachment de Collor. Cassado no escândalo dos anões do orçamento em 1994, depois inocentado, voltou à Câmara em 2007.",
 "Why here: PMDB, 108 seats in 1990, was the pivot of the House with no programme of its own.",
 "Por que aqui: o PMDB, com 108 cadeiras em 1990, era o pivô da Casa sem programa próprio."),
(1990,"centre_left","Miguel Arraes","PSB · PE",
 "Born 1916, Araripe (CE); died 2005. Law degree, Recife Law School. Mayor of Recife and governor of Pernambuco 1963–64, deposed and jailed by the coup, exiled in Algeria until 1979. Federal deputy in 1990 (most voted in Pernambuco), governor again 1995–98, PSB national president.",
 "Nascido em 1916, Araripe (CE); morreu em 2005. Bacharel pela Faculdade de Direito do Recife. Prefeito do Recife e governador de Pernambuco 1963–64, deposto e preso pelo golpe, exilado na Argélia até 1979. Deputado federal em 1990 (o mais votado de Pernambuco), governador de novo em 1995–98, presidente nacional do PSB.",
 "Why here: PSB and PDT carried the pre-1964 reformist tradition into the New Republic.",
 "Por que aqui: PSB e PDT levaram a tradição reformista pré-1964 para a Nova República."),
(1990,"left","Luiz Inácio Lula da Silva","PT · SP",
 "Born 1945, Caetés (PE). Lathe operator trained at SENAI; no university. Led the metalworkers' strikes of 1978–80, founded PT in 1980 and CUT in 1983, federal deputy 1987–91 (most voted in the country), lost the 1989 run-off to Collor by 6 points.",
 "Nascido em 1945, Caetés (PE). Torneiro mecânico formado pelo SENAI; sem curso superior. Liderou as greves metalúrgicas de 1978–80, fundou o PT em 1980 e a CUT em 1983, deputado federal 1987–91 (o mais votado do país), perdeu o segundo turno de 1989 para Collor por 6 pontos.",
 "Why here: the PT of 1990 was a union-and-church party with a socialist programme — the reference point for the 'left' bin.",
 "Por que aqui: o PT de 1990 era um partido de sindicatos e igreja com programa socialista — a referência da faixa 'esquerda'."),
(1990,"far_left","Roberto Freire","PCB · PE",
 "Born 1942, Recife. Law degree, Federal University of Pernambuco. Federal deputy from 1979, president of the Brazilian Communist Party and its presidential candidate in 1989 (1.1%). In 1992 he led the party's refoundation as PPS, drifting to the centre; senator 1995–2003, Minister of Culture under Temer.",
 "Nascido em 1942, Recife. Bacharel em Direito pela UFPE. Deputado federal desde 1979, presidente do Partido Comunista Brasileiro e seu candidato à Presidência em 1989 (1,1%). Em 1992 conduziu a refundação como PPS, deslocando-se ao centro; senador 1995–2003, ministro da Cultura de Temer.",
 "Why here: the three PCB deputies of 1990 are the decade's only far-left seats.",
 "Por que aqui: os três deputados do PCB em 1990 são as únicas cadeiras de extrema esquerda da década."),
# ───────────────────────── 1994 ─────────────────────────
(1994,"far_right","Jair Bolsonaro","PPR · RJ",
 "Born 1955, Glicério (SP). Army captain, Military Academy of Agulhas Negras (1977), paratrooper, retired in 1988 after a disciplinary case. City councillor in Rio (1989), federal deputy from 1991 (PDC, then PPR/PPB), speaking for military and police pay and against the 1988 Constitution's amnesty provisions.",
 "Nascido em 1955, Glicério (SP). Capitão do Exército, formado na AMAN (1977), paraquedista, reformado em 1988 após processo disciplinar. Vereador no Rio (1989), deputado federal a partir de 1991 (PDC, depois PPR/PPB), defendendo os salários de militares e policiais e atacando a anistia da Constituição de 1988.",
 "Why here: his party (PPR) is mapped as right; he is listed because the far-right persona existed inside the centrão long before it had a party. PRONA had no seats.",
 "Por que aqui: seu partido (PPR) é mapeado como direita; ele aparece porque a persona de extrema direita existia dentro do centrão muito antes de ter partido. O PRONA não tinha cadeiras."),
(1994,"right","Antônio Carlos Magalhães","PFL · BA",
 "Born 1927, Salvador; died 2007. Physician, Federal University of Bahia. Governor of Bahia three times (two under the regime, one elected in 1990), Minister of Communications under Sarney, elected senator in 1994, president of the Senate 1997–2001. Built the PFL's Bahia machine and was FHC's main ally.",
 "Nascido em 1927, Salvador; morreu em 2007. Médico pela UFBA. Governador da Bahia três vezes (duas no regime, uma eleito em 1990), ministro das Comunicações de Sarney, eleito senador em 1994, presidente do Senado 1997–2001. Construiu a máquina do PFL na Bahia e foi o principal aliado de FHC.",
 "Why here: PFL's 89 seats in 1994 anchored the FHC coalition from the right.",
 "Por que aqui: as 89 cadeiras do PFL em 1994 ancoraram a coalizão de FHC pela direita."),
(1994,"centre_right","Fernando Henrique Cardoso","PSDB · SP",
 "Born 1931, Rio de Janeiro. Sociologist, University of São Paulo (doctorate 1961), exiled in 1964, co-founder of CEBRAP. Senator 1983–92, co-founder of PSDB in 1988, Finance Minister 1993–94 (Real Plan), elected president in the first round of 1994 and re-elected in 1998.",
 "Nascido em 1931, Rio de Janeiro. Sociólogo pela USP (doutorado em 1961), exilado em 1964, cofundador do CEBRAP. Senador 1983–92, cofundador do PSDB em 1988, ministro da Fazenda 1993–94 (Plano Real), eleito presidente no primeiro turno de 1994 e reeleito em 1998.",
 "Why here: 1994 is when PSDB moves from centre to centre-right in the mapping, by governing with PFL.",
 "Por que aqui: 1994 é quando o PSDB passa do centro à centro-direita no mapeamento, ao governar com o PFL."),
(1994,"centre","Itamar Franco","PMDB · MG",
 "Born 1930, at sea (registered in Salvador); died 2011. Civil engineer, Federal University of Juiz de Fora. Mayor of Juiz de Fora, senator 1975–92, Collor's vice-president, president 1992–94 after the impeachment, launching the Real Plan. Later governor of Minas Gerais (1999–2002) and senator again.",
 "Nascido em 1930, em alto-mar (registrado em Salvador); morreu em 2011. Engenheiro civil pela UFJF. Prefeito de Juiz de Fora, senador 1975–92, vice de Collor, presidente 1992–94 após o impeachment, lançando o Plano Real. Depois governador de Minas (1999–2002) e senador de novo.",
 "Why here: the PMDB of the transition — a nationalist from the old MDB presiding over a government of everyone.",
 "Por que aqui: o PMDB da transição — um nacionalista do velho MDB presidindo um governo de todos."),
(1994,"centre_left","Leonel Brizola","PDT · RJ",
 "Born 1922, Carazinho; died 2004. Civil engineer, Federal University of Rio Grande do Sul. Governor of Rio Grande do Sul 1959–63 (led the 1961 'Legality' campaign), exiled 1964–79, founded PDT in 1980, governor of Rio de Janeiro 1983–87 and 1991–94, presidential candidate in 1989 (third, 16%) and 1994 (3%).",
 "Nascido em 1922, Carazinho; morreu em 2004. Engenheiro civil pela UFRGS. Governador do Rio Grande do Sul 1959–63 (liderou a Campanha da Legalidade em 1961), exilado 1964–79, fundou o PDT em 1980, governador do Rio 1983–87 e 1991–94, candidato à Presidência em 1989 (terceiro, 16%) e 1994 (3%).",
 "Why here: PDT's Vargas-style labourism was the clearest centre-left identity of the 1990s.",
 "Por que aqui: o trabalhismo varguista do PDT era a identidade de centro-esquerda mais nítida dos anos 1990."),
(1994,"left","Marta Suplicy","PT · SP",
 "Born 1945, São Paulo. Psychologist, PUC-SP, with postgraduate work at Stanford; became nationally known as a TV sexologist in the 1980s. Elected federal deputy in 1994, mayor of São Paulo 2001–04, Minister of Tourism and of Culture under Lula and Dilma, senator 2011–19. Left PT in 2015 and later returned.",
 "Nascida em 1945, São Paulo. Psicóloga pela PUC-SP, com pós-graduação em Stanford; ficou conhecida como sexóloga de TV nos anos 1980. Eleita deputada federal em 1994, prefeita de São Paulo 2001–04, ministra do Turismo e da Cultura de Lula e Dilma, senadora 2011–19. Saiu do PT em 2015 e voltou depois.",
 "Why here: PT's 1994 bench (49 seats) was its first large one; Marta is the party's upper-middle-class, customs-liberal wing.",
 "Por que aqui: a bancada petista de 1994 (49 cadeiras) foi a primeira grande; Marta é a ala de classe média alta e liberal nos costumes do partido."),
(1994,"far_left","José Maria de Almeida","PSTU · SP",
 "Born 1957, Sorocaba. Metalworker; no university. Union leader in the ABC region alongside Lula, member of PT's Trotskyist tendency Convergência Socialista, expelled in 1992, founded PSTU in 1994 and ran for president in 1998, 2002, 2006 and 2010 (never above 0.5%). No seats.",
 "Nascido em 1957, Sorocaba. Metalúrgico; sem curso superior. Dirigente sindical no ABC ao lado de Lula, membro da tendência trotskista Convergência Socialista do PT, expulso em 1992, fundou o PSTU em 1994 e disputou a Presidência em 1998, 2002, 2006 e 2010 (nunca acima de 0,5%). Sem cadeiras.",
 "Why here: from 1994 to 2002 the far left had no deputies; PSTU is the reference organisation.",
 "Por que aqui: de 1994 a 2002 a extrema esquerda não teve deputados; o PSTU é a organização de referência."),
# ───────────────────────── 1998 ─────────────────────────
(1998,"far_right","Enéas Carneiro","PRONA · SP",
 "Born 1938, Rio Branco. Physician and cardiologist. Third in the 1994 presidential election (7.4%) on a nationalist, anti-globalisation platform; ran again in 1998 (2.1%). PRONA elected its first federal deputy in 1998, in São Paulo, on his coattails.",
 "Nascido em 1938, Rio Branco. Médico cardiologista. Terceiro na eleição presidencial de 1994 (7,4%) com plataforma nacionalista e antiglobalização; disputou de novo em 1998 (2,1%). O PRONA elegeu seu primeiro deputado federal em 1998, em São Paulo, na esteira de sua votação.",
 "Why here: the single far-right seat of 1998 is PRONA's.",
 "Por que aqui: a única cadeira de extrema direita em 1998 é do PRONA."),
(1998,"right","Inocêncio Oliveira","PFL · PE",
 "Born 1938, Serra Talhada (PE). Physician, Federal University of Pernambuco. Federal deputy for Pernambuco from 1975 (ARENA) to 2015, president of the Chamber 1993–95, and the PFL's sertão strongman; later PL and PR. One of the longest-serving deputies in the House's history.",
 "Nascido em 1938, Serra Talhada (PE). Médico pela UFPE. Deputado federal por Pernambuco de 1975 (ARENA) a 2015, presidente da Câmara 1993–95, cacique do PFL no sertão; depois PL e PR. Um dos deputados mais longevos da história da Casa.",
 "Why here: the PFL's 105 seats in 1998 were its peak; Inocêncio is its rural, clientelist core.",
 "Por que aqui: as 105 cadeiras do PFL em 1998 foram seu auge; Inocêncio é seu núcleo rural e clientelista."),
(1998,"centre_right","Mário Covas","PSDB · SP",
 "Born 1930, Santos; died 2001. Civil engineer, Polytechnic School of USP. Federal deputy from 1963, MDB leader stripped of his mandate in 1969, mayor of São Paulo 1983–85, senator and PMDB leader in the Constituent Assembly, co-founder of PSDB, governor of São Paulo 1995–2001, re-elected in 1998.",
 "Nascido em 1930, Santos; morreu em 2001. Engenheiro civil pela Poli-USP. Deputado federal desde 1963, líder do MDB cassado em 1969, prefeito de São Paulo 1983–85, senador e líder do PMDB na Constituinte, cofundador do PSDB, governador de São Paulo 1995–2001, reeleito em 1998.",
 "Why here: PSDB's 99 seats in 1998 made it the largest centre-right bench; Covas was its ethical reference.",
 "Por que aqui: as 99 cadeiras do PSDB em 1998 fizeram dele a maior bancada de centro-direita; Covas era sua referência ética."),
(1998,"centre","Jader Barbalho","PMDB · PA",
 "Born 1944, Belém. Law degree, Federal University of Pará. Governor of Pará 1983–87 and 1991–94, minister under Sarney and Itamar, senator from 1995, president of the Senate in 2001 (resigned amid corruption charges), senator again from 2011. Head of Pará's dominant political family.",
 "Nascido em 1944, Belém. Bacharel em Direito pela UFPA. Governador do Pará 1983–87 e 1991–94, ministro de Sarney e Itamar, senador a partir de 1995, presidente do Senado em 2001 (renunciou sob acusações de corrupção), senador de novo a partir de 2011. Chefe da família política dominante do Pará.",
 "Why here: regional oligarchies with no ideological programme are what the PMDB bench is made of.",
 "Por que aqui: oligarquias regionais sem programa ideológico são a matéria-prima da bancada do PMDB."),
(1998,"centre_left","Ciro Gomes","PPS · CE",
 "Born 1957, Pindamonhangaba (SP). Law degree, Federal University of Ceará. Mayor of Fortaleza, governor of Ceará 1991–94, Finance Minister in 1994, presidential candidate in 1998 (third, 11%) and 2002 (PPS), Minister of National Integration under Lula, later PSB and PDT; presidential candidate again in 2018 and 2022.",
 "Nascido em 1957, Pindamonhangaba (SP). Bacharel em Direito pela UFC. Prefeito de Fortaleza, governador do Ceará 1991–94, ministro da Fazenda em 1994, candidato à Presidência em 1998 (terceiro, 11%) e 2002 (PPS), ministro da Integração Nacional de Lula, depois PSB e PDT; candidato de novo em 2018 e 2022.",
 "Why here: PPS in 1998 was the social-democratic heir of the PCB, before its drift to the centre.",
 "Por que aqui: o PPS de 1998 era o herdeiro social-democrata do PCB, antes do deslocamento para o centro."),
(1998,"left","Aloizio Mercadante","PT · SP",
 "Born 1954, Santos. Economist, University of São Paulo; master's and doctorate at Unicamp, where he taught. PT founder, federal deputy 1991–95 and 1999–2003, Lula's running mate in 1994, senator 2003–10, Minister of Science, Education and Chief of Staff under Dilma, president of BNDES since 2023.",
 "Nascido em 1954, Santos. Economista pela USP; mestre e doutor pela Unicamp, onde foi professor. Fundador do PT, deputado federal 1991–95 e 1999–2003, vice de Lula em 1994, senador 2003–10, ministro da Ciência, da Educação e da Casa Civil de Dilma, presidente do BNDES desde 2023.",
 "Why here: the economist wing that wrote PT's developmentalist programme for the 2000s.",
 "Por que aqui: a ala de economistas que escreveu o programa desenvolvimentista do PT para os anos 2000."),
(1998,"far_left","Rui Costa Pimenta","PCO · SP",
 "Born 1957, São Paulo. Journalist. Founded the Workers' Cause Party (PCO) in 1995 after his Trotskyist current left PT; presidential candidate in 2002, 2006, 2010, 2014, 2018 and 2022, never reaching 0.1%. Runs the party's newspaper and online channel. No seats.",
 "Nascido em 1957, São Paulo. Jornalista. Fundou o Partido da Causa Operária (PCO) em 1995 após sua corrente trotskista deixar o PT; candidato à Presidência em 2002, 2006, 2010, 2014, 2018 e 2022, nunca chegando a 0,1%. Dirige o jornal e o canal do partido. Sem cadeiras.",
 "Why here: no far-left deputies in 1998; PCO and PSTU were the organisations standing.",
 "Por que aqui: nenhum deputado de extrema esquerda em 1998; PCO e PSTU eram as organizações de pé."),
# ───────────────────────── 2002 ─────────────────────────
(2002,"far_right","Enéas Carneiro","PRONA · SP",
 "Born 1938, Rio Branco; died 2007. Physician and cardiologist. After three presidential runs, elected federal deputy for São Paulo in 2002 with 1.57 million votes, then the largest tally in Brazilian history, dragging five unknown PRONA candidates into the Chamber with him. Re-elected in 2006.",
 "Nascido em 1938, Rio Branco; morreu em 2007. Médico cardiologista. Depois de três candidaturas presidenciais, eleito deputado federal por São Paulo em 2002 com 1,57 milhão de votos, então a maior votação da história, puxando cinco candidatos desconhecidos do PRONA para a Câmara. Reeleito em 2006.",
 "Why here: the six PRONA seats of 2002 are the far-right column's high point before 2018.",
 "Por que aqui: as seis cadeiras do PRONA em 2002 são o auge da coluna da extrema direita antes de 2018."),
(2002,"right","Delfim Netto","PPB · SP",
 "Born 1928, São Paulo; died 2024. Economist, University of São Paulo, professor there. Finance Minister 1967–74 (the 'economic miracle') and Planning Minister 1979–85 under the military regime, ambassador to France. Federal deputy for São Paulo 1987–2007 (PDS, PPR, PPB, PP, PMDB), later an informal adviser to Lula.",
 "Nascido em 1928, São Paulo; morreu em 2024. Economista pela USP, onde foi professor. Ministro da Fazenda 1967–74 (o 'milagre econômico') e do Planejamento 1979–85 no regime militar, embaixador na França. Deputado federal por São Paulo 1987–2007 (PDS, PPR, PPB, PP, PMDB), depois conselheiro informal de Lula.",
 "Why here: PPB in 2002 was still the party of the regime's economic establishment.",
 "Por que aqui: o PPB em 2002 ainda era o partido do establishment econômico do regime."),
(2002,"centre_right","José Serra","PSDB · SP",
 "Born 1942, São Paulo. Engineering student and student-union president in 1963, exiled after the coup; master's in economics (Chile), PhD in economics (Cornell). Health Minister under FHC (generic drugs), presidential candidate in 2002 (lost the run-off to Lula) and 2010, mayor and governor of São Paulo, Foreign Minister under Temer, senator.",
 "Nascido em 1942, São Paulo. Estudante de engenharia e presidente da UNE em 1963, exilado após o golpe; mestre em Economia (Chile), doutor em Economia (Cornell). Ministro da Saúde de FHC (genéricos), candidato à Presidência em 2002 (perdeu o segundo turno para Lula) e 2010, prefeito e governador de São Paulo, chanceler de Temer, senador.",
 "Why here: the technocratic, fiscally orthodox PSDB that became the opposition to PT from the centre-right.",
 "Por que aqui: o PSDB tecnocrático e ortodoxo que virou a oposição ao PT pela centro-direita."),
(2002,"centre","José Sarney","PMDB · AP",
 "Born 1930, Pinheiro (MA). Law degree, Federal University of Maranhão; writer, member of the Brazilian Academy of Letters. Governor of Maranhão, ARENA/PDS president, Tancredo Neves's running mate and president 1985–90 after Tancredo's death. Senator for Amapá from 1991, president of the Senate three times.",
 "Nascido em 1930, Pinheiro (MA). Bacharel em Direito pela UFMA; escritor, membro da Academia Brasileira de Letras. Governador do Maranhão, presidente da ARENA/PDS, vice de Tancredo Neves e presidente 1985–90 após a morte de Tancredo. Senador pelo Amapá desde 1991, presidente do Senado três vezes.",
 "Why here: from the regime's party to Lula's coalition — the centre as continuity of power.",
 "Por que aqui: do partido do regime à coalizão de Lula — o centro como continuidade do poder."),
(2002,"centre_left","Eduardo Campos","PSB · PE",
 "Born 1965, Recife; died 2014. Economist, Federal University of Pernambuco; grandson of Miguel Arraes. State deputy, elected federal deputy in 2002 as the most voted in Pernambuco, Minister of Science and Technology under Lula, governor of Pernambuco 2007–14, PSB president, presidential candidate in 2014, killed in a plane crash.",
 "Nascido em 1965, Recife; morreu em 2014. Economista pela UFPE; neto de Miguel Arraes. Deputado estadual, eleito deputado federal em 2002 como o mais votado de Pernambuco, ministro da Ciência e Tecnologia de Lula, governador de Pernambuco 2007–14, presidente do PSB, candidato à Presidência em 2014, morto em acidente aéreo.",
 "Why here: PSB as PT's ally-but-not-subordinate — it broke with Dilma in 2013 to run its own candidate.",
 "Por que aqui: o PSB como aliado, mas não subordinado, do PT — rompeu com Dilma em 2013 para lançar candidato próprio."),
(2002,"left","Luiz Inácio Lula da Silva","PT · SP",
 "Born 1945, Caetés (PE). Lathe operator, SENAI. Elected president in 2002 on his fourth attempt, after the 'Letter to the Brazilian People' promising fiscal continuity; PT elected 91 deputies, its largest bench. Governed 2003–10 with the centrão, Bolsa Família and the commodity boom; re-elected in 2022.",
 "Nascido em 1945, Caetés (PE). Torneiro mecânico pelo SENAI. Eleito presidente em 2002 na quarta tentativa, após a 'Carta ao Povo Brasileiro' prometendo continuidade fiscal; o PT elegeu 91 deputados, sua maior bancada. Governou 2003–10 com o centrão, o Bolsa Família e o boom das commodities; reeleito em 2022.",
 "Why here: 2002 is the moment PT moderates — the reason expert surveys later place it near the centre-left.",
 "Por que aqui: 2002 é o momento em que o PT se modera — a razão de pesquisas com especialistas o colocarem depois perto da centro-esquerda."),
(2002,"far_left","Luciana Genro","PT → PSOL · RS",
 "Born 1971, Santa Maria (RS). Lawyer, trained at Unisinos; daughter of Tarso Genro. State deputy 1995–2003, elected federal deputy in 2002 for PT, expelled in 2003 for voting against Lula's pension reform; co-founder and first Chamber leader of PSOL, presidential candidate in 2014 (1.6 million votes), state deputy again since 2019.",
 "Nascida em 1971, Santa Maria (RS). Advogada formada na Unisinos; filha de Tarso Genro. Deputada estadual 1995–2003, eleita deputada federal em 2002 pelo PT, expulsa em 2003 por votar contra a reforma da previdência de Lula; cofundadora e primeira líder do PSOL na Câmara, candidata à Presidência em 2014 (1,6 milhão de votos), deputada estadual de novo desde 2019.",
 "Why here: elected by PT in 2002, she became the far left's first deputy when PSOL was founded in 2004.",
 "Por que aqui: eleita pelo PT em 2002, tornou-se a primeira deputada da extrema esquerda com a fundação do PSOL em 2004."),
# ───────────────────────── 2006 ─────────────────────────
(2006,"far_right","Jair Bolsonaro","PP · RJ",
 "Born 1955, Glicério (SP). Retired army captain (AMAN 1977). Re-elected federal deputy in 2006 for PP, his fifth term, with a small Rio constituency of military families and police; known in the House for provocations on the dictatorship, gun rights and sexuality, and for voting with the centrão on everything else.",
 "Nascido em 1955, Glicério (SP). Capitão reformado do Exército (AMAN 1977). Reeleito deputado federal em 2006 pelo PP, seu quinto mandato, com um eleitorado carioca de famílias militares e policiais; conhecido na Casa pelas provocações sobre a ditadura, armas e sexualidade, e por votar com o centrão em todo o resto.",
 "Why here: PRONA's two seats (Enéas, re-elected) are the only far-right ones in 2006; Bolsonaro's party is mapped as right.",
 "Por que aqui: as duas cadeiras do PRONA (Enéas, reeleito) são as únicas de extrema direita em 2006; o partido de Bolsonaro é mapeado como direita."),
(2006,"right","Paulo Maluf","PP · SP",
 "Born 1931, São Paulo. Civil engineer, Polytechnic School of USP. Mayor of São Paulo (appointed 1969–71; elected 1993–96), governor 1979–82 (indirect), presidential candidate in 1985 and 1989, elected federal deputy in 2006 and 2010 and 2014; convicted of money laundering in 2017.",
 "Nascido em 1931, São Paulo. Engenheiro civil pela Poli-USP. Prefeito de São Paulo (nomeado 1969–71; eleito 1993–96), governador 1979–82 (indireto), candidato à Presidência em 1985 e 1989, eleito deputado federal em 2006, 2010 e 2014; condenado por lavagem de dinheiro em 2017.",
 "Why here: PP under Maluf was the hard right of the ARENA lineage, before dissolving into the centrão after 2010.",
 "Por que aqui: o PP de Maluf era a direita dura da linhagem da ARENA, antes de se diluir no centrão depois de 2010."),
(2006,"centre_right","Geraldo Alckmin","PSDB · SP",
 "Born 1952, Pindamonhangaba (SP). Physician, University of Taubaté. Mayor of Pindamonhangaba, federal deputy, PSDB co-founder, governor of São Paulo 2001–06 and 2011–18, presidential candidate in 2006 (lost the run-off to Lula) and 2018. Left PSDB in 2021 and became Lula's vice-president in 2023 (PSB).",
 "Nascido em 1952, Pindamonhangaba (SP). Médico pela Universidade de Taubaté. Prefeito de Pindamonhangaba, deputado federal, cofundador do PSDB, governador de São Paulo 2001–06 e 2011–18, candidato à Presidência em 2006 (perdeu o segundo turno para Lula) e 2018. Saiu do PSDB em 2021 e virou vice de Lula em 2023 (PSB).",
 "Why here: Opus Dei Catholic and fiscal conservative — PSDB's socially conservative wing.",
 "Por que aqui: católico da Opus Dei e conservador fiscal — a ala socialmente conservadora do PSDB."),
(2006,"centre","Renan Calheiros","PMDB · AL",
 "Born 1955, Murici (AL). Law degree, Federal University of Alagoas. Federal deputy from 1983, Collor's ally then Justice Minister under FHC, senator since 1995, president of the Senate 2005–07 (resigned under investigation) and 2013–17, PMDB leader in the Senate; Lula's and Dilma's ally, then Temer's.",
 "Nascido em 1955, Murici (AL). Bacharel em Direito pela UFAL. Deputado federal desde 1983, aliado de Collor e depois ministro da Justiça de FHC, senador desde 1995, presidente do Senado 2005–07 (renunciou sob investigação) e 2013–17, líder do PMDB no Senado; aliado de Lula e Dilma, depois de Temer.",
 "Why here: the centre as the permanent governing partner of whoever wins.",
 "Por que aqui: o centro como sócio permanente de quem governa."),
(2006,"centre_left","Ciro Gomes","PSB · CE",
 "Born 1957, Pindamonhangaba (SP). Law degree, Federal University of Ceará. Elected federal deputy in 2006 for PSB as the most voted in Ceará, after serving as Lula's Minister of National Integration; later PROS and PDT, presidential candidate in 2018 (third, 12%) and 2022.",
 "Nascido em 1957, Pindamonhangaba (SP). Bacharel em Direito pela UFC. Eleito deputado federal em 2006 pelo PSB como o mais votado do Ceará, depois de ser ministro da Integração Nacional de Lula; depois PROS e PDT, candidato à Presidência em 2018 (terceiro, 12%) e 2022.",
 "Why here: developmentalist, nationalist centre-left inside the Lula coalition.",
 "Por que aqui: centro-esquerda desenvolvimentista e nacionalista dentro da coalizão de Lula."),
(2006,"left","Jaques Wagner","PT · BA",
 "Born 1951, Rio de Janeiro. Studied engineering at UFRJ without finishing; petrochemical worker and union leader in Camaçari. Federal deputy 1991–2003, Lula's Minister of Labour, elected governor of Bahia in 2006 ending the Carlista era, re-elected 2010, Minister of Defence and Chief of Staff under Dilma, senator since 2019.",
 "Nascido em 1951, Rio de Janeiro. Cursou engenharia na UFRJ sem concluir; operário petroquímico e dirigente sindical em Camaçari. Deputado federal 1991–2003, ministro do Trabalho de Lula, eleito governador da Bahia em 2006 encerrando a era carlista, reeleito em 2010, ministro da Defesa e da Casa Civil de Dilma, senador desde 2019.",
 "Why here: PT's 2006 conquest of the Northeast state governments is what made it a party of government.",
 "Por que aqui: a conquista dos governos estaduais do Nordeste em 2006 é o que fez do PT um partido de governo."),
(2006,"far_left","Heloísa Helena","PSOL · AL",
 "Born 1962, Pão de Açúcar (AL). Nurse, Federal University of Alagoas, where she taught. City councillor, state deputy, senator 2003–11 (elected by PT), expelled from PT in 2003 over the pension reform vote, co-founder of PSOL, presidential candidate in 2006 (third, 6.85%). Later in Rede.",
 "Nascida em 1962, Pão de Açúcar (AL). Enfermeira pela UFAL, onde foi professora. Vereadora, deputada estadual, senadora 2003–11 (eleita pelo PT), expulsa do PT em 2003 pelo voto na reforma da previdência, cofundadora do PSOL, candidata à Presidência em 2006 (terceira, 6,85%). Depois na Rede.",
 "Why here: PSOL's first national face; the party elected its first three deputies in 2006.",
 "Por que aqui: o primeiro rosto nacional do PSOL; o partido elegeu seus três primeiros deputados em 2006."),
# ───────────────────────── 2010 ─────────────────────────
(2010,"far_right","Jair Bolsonaro","PP · RJ",
 "Born 1955, Glicério (SP). Retired army captain. Re-elected in 2010 with 120,000 votes, his sixth term. Voted for military pay, against the Truth Commission (2011) and against the government's human-rights and education programmes; dedicated his 2016 impeachment vote to the colonel who tortured Dilma Rousseff.",
 "Nascido em 1955, Glicério (SP). Capitão reformado. Reeleito em 2010 com 120 mil votos, sexto mandato. Votou por salários militares, contra a Comissão da Verdade (2011) e contra os programas de direitos humanos e educação do governo; dedicou seu voto no impeachment de 2016 ao coronel que torturou Dilma Rousseff.",
 "Why here: no far-right seats in 2010 (PRONA merged into PR); the persona persists inside PP.",
 "Por que aqui: nenhuma cadeira de extrema direita em 2010 (o PRONA se fundiu no PR); a persona persiste dentro do PP."),
(2010,"right","Marco Feliciano","PSC · SP",
 "Born 1972, Orlândia (SP). Assemblies of God pastor; studied theology. Elected federal deputy in 2010 with 212,000 votes, president of the Human Rights Commission in 2013 amid protests over his statements on homosexuality and race; re-elected in 2014, 2018 and 2022 (Podemos, then PL).",
 "Nascido em 1972, Orlândia (SP). Pastor da Assembleia de Deus; estudou teologia. Eleito deputado federal em 2010 com 212 mil votos, presidente da Comissão de Direitos Humanos em 2013 em meio a protestos por declarações sobre homossexualidade e raça; reeleito em 2014, 2018 e 2022 (Podemos, depois PL).",
 "Why here: PSC and PRB were the evangelical right before it was absorbed by Bolsonarism.",
 "Por que aqui: PSC e PRB eram a direita evangélica antes de ser absorvida pelo bolsonarismo."),
(2010,"centre_right","Aécio Neves","PSDB · MG",
 "Born 1960, Belo Horizonte. Economist, PUC Minas; grandson of Tancredo Neves. Federal deputy from 1987, president of the Chamber 2001–02, governor of Minas Gerais 2003–10, elected senator in 2010 with a record vote, PSDB president, lost the 2014 run-off to Dilma by 3 points; federal deputy since 2019.",
 "Nascido em 1960, Belo Horizonte. Economista pela PUC Minas; neto de Tancredo Neves. Deputado federal desde 1987, presidente da Câmara 2001–02, governador de Minas 2003–10, eleito senador em 2010 com votação recorde, presidente do PSDB, perdeu o segundo turno de 2014 para Dilma por 3 pontos; deputado federal desde 2019.",
 "Why here: PSDB's 'management shock' modernising brand at its peak.",
 "Por que aqui: a marca modernizadora do 'choque de gestão' do PSDB em seu auge."),
(2010,"centre","Michel Temer","PMDB · SP",
 "Born 1940, Tietê (SP). Law degree, USP; doctorate in public law, PUC-SP, constitutional-law professor. Federal deputy from 1987, president of the Chamber 1997–2001 and 2009–10, PMDB president from 2001, Dilma's vice-president from 2011, president 2016–18 after her impeachment.",
 "Nascido em 1940, Tietê (SP). Bacharel em Direito pela USP; doutor em Direito Público pela PUC-SP, professor de Direito Constitucional. Deputado federal desde 1987, presidente da Câmara 1997–2001 e 2009–10, presidente do PMDB desde 2001, vice de Dilma desde 2011, presidente 2016–18 após o impeachment dela.",
 "Why here: the PMDB that joined Dilma's ticket in 2010 and replaced her in 2016.",
 "Por que aqui: o PMDB que entrou na chapa de Dilma em 2010 e a substituiu em 2016."),
(2010,"centre_left","Eduardo Campos","PSB · PE",
 "Born 1965, Recife; died 2014. Economist, UFPE. Re-elected governor of Pernambuco in 2010 with 82% of the vote, the largest margin in the country, on a record of industrial investment (Suape, the refinery) and education reform; PSB president, he broke with Dilma in 2013 to run for president.",
 "Nascido em 1965, Recife; morreu em 2014. Economista pela UFPE. Reeleito governador de Pernambuco em 2010 com 82% dos votos, a maior margem do país, com um histórico de investimento industrial (Suape, refinaria) e reforma educacional; presidente do PSB, rompeu com Dilma em 2013 para disputar a Presidência.",
 "Why here: PSB at its strongest (34 seats in 2010) and most independent.",
 "Por que aqui: o PSB em seu momento mais forte (34 cadeiras em 2010) e mais independente."),
(2010,"left","Dilma Rousseff","PT · RS",
 "Born 1947, Belo Horizonte. Economist, Federal University of Rio Grande do Sul. Armed-resistance militant, imprisoned and tortured 1970–72. PDT until 2001, then PT; Minister of Mines and Energy and Chief of Staff under Lula, elected president in 2010 and re-elected in 2014, removed by impeachment in 2016. President of the BRICS bank since 2023.",
 "Nascida em 1947, Belo Horizonte. Economista pela UFRGS. Militante da luta armada, presa e torturada em 1970–72. PDT até 2001, depois PT; ministra de Minas e Energia e da Casa Civil de Lula, eleita presidente em 2010 e reeleita em 2014, afastada por impeachment em 2016. Presidente do banco dos BRICS desde 2023.",
 "Why here: the PT of government — developmentalist state and coalition with the centrão.",
 "Por que aqui: o PT de governo — Estado desenvolvimentista e coalizão com o centrão."),
(2010,"far_left","Plínio de Arruda Sampaio","PSOL · SP",
 "Born 1930, São Paulo; died 2014. Law degree, University of São Paulo; public prosecutor. Federal deputy in 1962 (PDC), stripped of his mandate by the coup, exiled; PT founder, constituent deputy 1987–91, author of the agrarian-reform chapter. Left PT for PSOL in 2005 and was its presidential candidate in 2010 (0.9%).",
 "Nascido em 1930, São Paulo; morreu em 2014. Bacharel em Direito pela USP; promotor de Justiça. Deputado federal em 1962 (PDC), cassado pelo golpe, exilado; fundador do PT, deputado constituinte 1987–91, autor do capítulo da reforma agrária. Saiu do PT para o PSOL em 2005 e foi seu candidato à Presidência em 2010 (0,9%).",
 "Why here: the Catholic-left lineage of PSOL, as distinct from its Trotskyist one.",
 "Por que aqui: a linhagem católica de esquerda do PSOL, distinta da trotskista."),
# ───────────────────────── 2014 ─────────────────────────
(2014,"far_right","Eduardo Bolsonaro","PSC · SP",
 "Born 1984, Resende (RJ). Law degree, Federal University of Rio de Janeiro (2009); federal police clerk. Elected federal deputy for São Paulo in 2014 (PSC) with 82,000 votes; re-elected in 2018 with 1.84 million, the largest vote for a deputy in Brazilian history, and in 2022 (PL). His father's envoy to the Trump circle.",
 "Nascido em 1984, Resende (RJ). Bacharel em Direito pela UFRJ (2009); escrivão da Polícia Federal. Eleito deputado federal por São Paulo em 2014 (PSC) com 82 mil votos; reeleito em 2018 com 1,84 milhão, a maior votação para deputado da história, e em 2022 (PL). Emissário do pai junto ao círculo de Trump.",
 "Why here: 2014 is the last election with zero far-right seats; the Bolsonaro family's parties are still mapped as right.",
 "Por que aqui: 2014 é a última eleição com zero cadeiras de extrema direita; os partidos da família Bolsonaro ainda são mapeados como direita."),
(2014,"right","Rodrigo Maia","DEM · RJ",
 "Born 1970, Santiago, Chile (in exile). Studied economics at Cândido Mendes University; bank employee. Son of César Maia. Federal deputy from 1999, DEM national president, president of the Chamber 2016–21, where he steered the labour and pension reforms. Left DEM in 2021, now PSDB.",
 "Nascido em 1970, Santiago, Chile (no exílio). Cursou Economia na Universidade Cândido Mendes; bancário. Filho de César Maia. Deputado federal desde 1999, presidente nacional do DEM, presidente da Câmara 2016–21, onde conduziu as reformas trabalhista e da previdência. Saiu do DEM em 2021, hoje PSDB.",
 "Why here: DEM as the liberal, institutional right that never fused with Bolsonarism.",
 "Por que aqui: o DEM como a direita liberal e institucional que nunca se fundiu ao bolsonarismo."),
(2014,"centre_right","Gilberto Kassab","PSD · SP",
 "Born 1960, São Paulo. Civil engineer and economist, USP. City councillor, federal deputy (PFL), mayor of São Paulo 2006–12 (DEM), founder of PSD in 2011; the party elected 36 deputies in 2014, its first election. Minister under Dilma (Cities) and Temer (Science), São Paulo state secretary under Tarcísio.",
 "Nascido em 1960, São Paulo. Engenheiro civil e economista pela USP. Vereador, deputado federal (PFL), prefeito de São Paulo 2006–12 (DEM), fundador do PSD em 2011; o partido elegeu 36 deputados em 2014, sua primeira eleição. Ministro de Dilma (Cidades) e de Temer (Ciência), secretário estadual no governo Tarcísio.",
 "Why here: PSD was created to be the centrão — allied with PT, MDB and PL governments in sequence.",
 "Por que aqui: o PSD foi criado para ser o centrão — aliado de governos do PT, do MDB e do PL em sequência."),
(2014,"centre","Eduardo Cunha","PMDB · RJ",
 "Born 1958, Rio de Janeiro. Economist, Cândido Mendes University. Telerj president under Collor, federal deputy from 2003, PMDB leader, president of the Chamber 2015–16, where he opened Dilma's impeachment. Stripped of his mandate in 2016 and jailed under Lava Jato; released in 2020.",
 "Nascido em 1958, Rio de Janeiro. Economista pela Universidade Cândido Mendes. Presidente da Telerj no governo Collor, deputado federal desde 2003, líder do PMDB, presidente da Câmara 2015–16, onde abriu o impeachment de Dilma. Cassado em 2016 e preso na Lava Jato; solto em 2020.",
 "Why here: the centre as a transactional bloc, able to make or break a president.",
 "Por que aqui: o centro como bloco transacional, capaz de fazer ou derrubar um presidente."),
(2014,"centre_left","Marina Silva","PSB / Rede · AC",
 "Born 1958, Rio Branco. Rubber-tapper's daughter, literate at 16; history degree, Federal University of Acre. Chico Mendes's ally, PT senator 1995–2011, Lula's Environment Minister 2003–08, presidential candidate in 2010 (PV, 19%), 2014 (PSB, 21%) and 2018 (Rede); founded Rede in 2013; Environment Minister again since 2023.",
 "Nascida em 1958, Rio Branco. Filha de seringueiros, alfabetizada aos 16; licenciada em História pela UFAC. Aliada de Chico Mendes, senadora pelo PT 1995–2011, ministra do Meio Ambiente de Lula 2003–08, candidata à Presidência em 2010 (PV, 19%), 2014 (PSB, 21%) e 2018 (Rede); fundou a Rede em 2013; ministra do Meio Ambiente de novo desde 2023.",
 "Why here: the environmental centre-left outside PT, which ran against it in three elections.",
 "Por que aqui: a centro-esquerda ambiental fora do PT, que concorreu contra ele em três eleições."),
(2014,"left","Rui Costa","PT · BA",
 "Born 1963, Salvador. Economist, Federal University of Bahia. Chemical-industry union leader, city councillor, Jaques Wagner's chief of staff, elected governor of Bahia in 2014 and re-elected in 2018, Lula's Chief of Staff 2023–26, elected senator in 2026.",
 "Nascido em 1963, Salvador. Economista pela UFBA. Dirigente sindical da indústria química, vereador, chefe da Casa Civil de Jaques Wagner, eleito governador da Bahia em 2014 e reeleito em 2018, ministro da Casa Civil de Lula 2023–26, eleito senador em 2026.",
 "Why here: PT's Northeastern governing machine, which held through the party's national collapse.",
 "Por que aqui: a máquina governista do PT no Nordeste, que resistiu ao colapso nacional do partido."),
(2014,"far_left","Chico Alencar","PSOL · RJ",
 "Born 1949, Rio de Janeiro. History degree, Federal University of Rio de Janeiro; schoolteacher and textbook author. City councillor and state deputy for PT, federal deputy from 2003, left PT for PSOL in 2005 and was re-elected in 2006, 2010 and 2014; city councillor in Rio since 2021.",
 "Nascido em 1949, Rio de Janeiro. Licenciado em História pela UFRJ; professor e autor de livros didáticos. Vereador e deputado estadual pelo PT, deputado federal desde 2003, saiu do PT para o PSOL em 2005 e foi reeleito em 2006, 2010 e 2014; vereador no Rio desde 2021.",
 "Why here: PSOL's five seats in 2014 were still a parliamentary conscience vote, not a movement.",
 "Por que aqui: as cinco cadeiras do PSOL em 2014 ainda eram um voto de consciência parlamentar, não um movimento."),
# ───────────────────────── 2018 ─────────────────────────
(2018,"far_right","Jair Bolsonaro","PSL · RJ",
 "Born 1955, Glicério (SP). Retired army captain. After 27 years as a back-bench deputy, joined the tiny PSL in 2018 and won the presidency with 55% in the run-off against Haddad, carrying PSL from 1 to 52 seats. President 2019–22; barred from office until 2030 and convicted in 2025 for the coup plot.",
 "Nascido em 1955, Glicério (SP). Capitão reformado. Depois de 27 anos como deputado do baixo clero, filiou-se ao minúsculo PSL em 2018 e venceu a Presidência com 55% no segundo turno contra Haddad, levando o PSL de 1 a 52 cadeiras. Presidente 2019–22; inelegível até 2030 e condenado em 2025 pela trama golpista.",
 "Why here: 2018 is when the far-right column appears — PSL is mapped as far right for this election only.",
 "Por que aqui: 2018 é quando a coluna da extrema direita aparece — o PSL é mapeado como extrema direita só nesta eleição."),
(2018,"right","Marcel van Hattem","Novo · RS",
 "Born 1985. International relations, Federal University of Rio Grande do Sul; master's in political science, Leiden. City councillor in Dois Irmãos at 19, state deputy (PP), elected federal deputy in 2018 for Novo as the most voted in Rio Grande do Sul, the party's first Chamber leader; re-elected 2022 and 2026.",
 "Nascido em 1985. Relações Internacionais pela UFRGS; mestre em Ciência Política por Leiden. Vereador em Dois Irmãos aos 19 anos, deputado estadual (PP), eleito deputado federal em 2018 pelo Novo como o mais votado do Rio Grande do Sul, primeiro líder da bancada; reeleito em 2022 e 2026.",
 "Why here: Novo is the economic-liberal right, allied with Bolsonarism in votes but separate in origin.",
 "Por que aqui: o Novo é a direita liberal na economia, aliada do bolsonarismo nas votações mas de origem distinta."),
(2018,"centre_right","João Doria","PSDB · SP",
 "Born 1957, São Paulo. Journalism and public administration, FAAP; businessman and TV host. Mayor of São Paulo 2017–18, governor 2019–22, bought the CoronaVac vaccine and broke with Bolsonaro; won the PSDB presidential primary in 2021 but gave up the candidacy and left politics in 2022.",
 "Nascido em 1957, São Paulo. Jornalismo e Administração Pública pela FAAP; empresário e apresentador de TV. Prefeito de São Paulo 2017–18, governador 2019–22, comprou a CoronaVac e rompeu com Bolsonaro; venceu as prévias presidenciais do PSDB em 2021, mas desistiu da candidatura e deixou a política em 2022.",
 "Why here: PSDB's last attempt to hold a centre-right space between PT and Bolsonaro — it fell to 29 seats.",
 "Por que aqui: a última tentativa do PSDB de ocupar um espaço de centro-direita entre PT e Bolsonaro — caiu a 29 cadeiras."),
(2018,"centre","Henrique Meirelles","MDB · SP",
 "Born 1945, Anápolis (GO). Civil engineer, Polytechnic School of USP; MBA, COPPEAD-UFRJ. President of BankBoston, Central Bank governor 2003–10 under Lula, Finance Minister 2016–18 under Temer (spending cap, labour reform), MDB presidential candidate in 2018 (1.2%), São Paulo finance secretary under Doria.",
 "Nascido em 1945, Anápolis (GO). Engenheiro civil pela Poli-USP; MBA pela COPPEAD-UFRJ. Presidente do BankBoston, presidente do Banco Central 2003–10 com Lula, ministro da Fazenda 2016–18 com Temer (teto de gastos, reforma trabalhista), candidato do MDB à Presidência em 2018 (1,2%), secretário da Fazenda de São Paulo com Doria.",
 "Why here: served Lula and Temer alike — the centre's technocrat.",
 "Por que aqui: serviu a Lula e a Temer igualmente — o tecnocrata do centro."),
(2018,"centre_left","Ciro Gomes","PDT · CE",
 "Born 1957, Pindamonhangaba (SP). Law degree, UFC. Third in the 2018 presidential election with 12.5% for PDT, refusing to campaign for Haddad in the run-off; fourth in 2022 with 3%. The 'national-developmentalist' alternative to both PT and Bolsonarism.",
 "Nascido em 1957, Pindamonhangaba (SP). Bacharel em Direito pela UFC. Terceiro na eleição presidencial de 2018 com 12,5% pelo PDT, recusando-se a fazer campanha para Haddad no segundo turno; quarto em 2022 com 3%. A alternativa 'nacional-desenvolvimentista' tanto ao PT quanto ao bolsonarismo.",
 "Why here: PDT's 28 seats in 2018 were the centre-left's last large bench.",
 "Por que aqui: as 28 cadeiras do PDT em 2018 foram a última grande bancada da centro-esquerda."),
(2018,"left","Gleisi Hoffmann","PT · PR",
 "Born 1965, Curitiba. Law degree, Universidade Estadual de Londrina. Itaipu financial director, Dilma's Chief of Staff 2011–14, senator 2011–19, PT national president 2017–25 through Lula's imprisonment and release, elected federal deputy in 2018 and 2022, Minister of Institutional Relations since 2025.",
 "Nascida em 1965, Curitiba. Bacharel em Direito pela Universidade Estadual de Londrina. Diretora financeira de Itaipu, ministra da Casa Civil de Dilma 2011–14, senadora 2011–19, presidente nacional do PT 2017–25 durante a prisão e a soltura de Lula, eleita deputada federal em 2018 e 2022, ministra das Relações Institucionais desde 2025.",
 "Why here: the party in resistance mode — 'Lula livre' and the 2018 campaign without its candidate.",
 "Por que aqui: o partido em modo de resistência — 'Lula livre' e a campanha de 2018 sem seu candidato."),
(2018,"far_left","Guilherme Boulos","PSOL · SP",
 "Born 1982, São Paulo. Philosophy, USP; master's in psychiatry, USP. National coordinator of the Homeless Workers' Movement (MTST), PSOL presidential candidate in 2018 (0.6%), runner-up for mayor of São Paulo in 2020 and 2024, elected federal deputy in 2022 as the most voted in São Paulo, minister of the General Secretariat since October 2025.",
 "Nascido em 1982, São Paulo. Filosofia pela USP; mestre em Psiquiatria pela USP. Coordenador nacional do MTST, candidato do PSOL à Presidência em 2018 (0,6%), segundo colocado na prefeitura de São Paulo em 2020 e 2024, eleito deputado federal em 2022 como o mais votado de São Paulo, ministro da Secretaria-Geral desde outubro de 2025.",
 "Why here: PSOL doubled to 10 seats in 2018 and became a movement party rather than a conscience vote.",
 "Por que aqui: o PSOL dobrou para 10 cadeiras em 2018 e virou partido de movimento, não mais voto de consciência."),
# ───────────────────────── 2022 ─────────────────────────
(2022,"far_right","Nikolas Ferreira","PL · MG",
 "Born 1996, Belo Horizonte. Law degree, PUC Minas (2022). City councillor in Belo Horizonte (2020), elected federal deputy in 2022 with 1.49 million votes, the most voted in the country; built his following on social media around moral conservatism, gun rights and confrontation with the Supreme Court. Re-elected in 2026 with 3.1 million.",
 "Nascido em 1996, Belo Horizonte. Bacharel em Direito pela PUC Minas (2022). Vereador de Belo Horizonte (2020), eleito deputado federal em 2022 com 1,49 milhão de votos, o mais votado do país; construiu sua base nas redes sociais em torno do conservadorismo moral, do armamento e do confronto com o STF. Reeleito em 2026 com 3,1 milhões.",
 "Why here: PL after Bolsonaro's 2021 affiliation is mapped as far right; 99 seats in 2022.",
 "Por que aqui: o PL após a filiação de Bolsonaro em 2021 é mapeado como extrema direita; 99 cadeiras em 2022."),
(2022,"right","Hugo Motta","Republicanos · PB",
 "Born 1989, João Pessoa; heir of an MDB family from Patos. Physician. Federal deputy since 2010 (elected at 21), MDB until 2018, then Republicanos; re-elected in 2022; president of the Chamber of Deputies since February 2025.",
 "Nascido em 1989, João Pessoa; herdeiro de uma família do MDB de Patos. Médico. Deputado federal desde 2010 (eleito aos 21 anos), no MDB até 2018, depois no Republicanos; reeleito em 2022; presidente da Câmara dos Deputados desde fevereiro de 2025.",
 "Why here: Republicanos (41 seats in 2022) is the church-backed, coalition-pragmatic right.",
 "Por que aqui: o Republicanos (41 cadeiras em 2022) é a direita de base evangélica e pragmática em coalizões."),
(2022,"centre_right","Arthur Lira","PP · AL",
 "Born 1969, Maceió. Law degree, Federal University of Alagoas (1993). City councillor, state deputy, federal deputy since 2011, president of the Chamber 2021–25 under Bolsonaro and Lula, where he centralised control of the 'secret budget' amendments; PP's dominant figure.",
 "Nascido em 1969, Maceió. Bacharel em Direito pela UFAL (1993). Vereador, deputado estadual, deputado federal desde 2011, presidente da Câmara 2021–25 sob Bolsonaro e Lula, onde centralizou o controle das emendas do 'orçamento secreto'; figura dominante do PP.",
 "Why here: the centrão at the height of its power over the budget, under governments of both colours.",
 "Por que aqui: o centrão no auge de seu poder sobre o orçamento, sob governos das duas cores."),
(2022,"centre","Simone Tebet","MDB · MS",
 "Born 1970, Três Lagoas. Law degree, UFRJ; master's in constitutional law, PUC-SP. State deputy, mayor of Três Lagoas, vice-governor, senator 2015–23, third in the 2022 presidential election (4.2%) and decisive in endorsing Lula for the run-off; Minister of Planning since 2023.",
 "Nascida em 1970, Três Lagoas. Bacharel em Direito pela UFRJ; mestre em Direito do Estado pela PUC-SP. Deputada estadual, prefeita de Três Lagoas, vice-governadora, senadora 2015–23, terceira na eleição presidencial de 2022 (4,2%) e decisiva ao apoiar Lula no segundo turno; ministra do Planejamento desde 2023.",
 "Why here: MDB's 42 seats in 2022 and its split between Lula and Bolsonaro supporters.",
 "Por que aqui: as 42 cadeiras do MDB em 2022 e sua divisão entre apoiadores de Lula e de Bolsonaro."),
(2022,"centre_left","Tabata Amaral","PSB · SP",
 "Born 1993, São Paulo (Vila Missionária). Astrophysics and political science, Harvard (2016). Federal deputy in 2018 (PDT) and 2022 (PSB), focused on education; ran for mayor of São Paulo in 2024; re-elected in 2026 with 476,000 votes.",
 "Nascida em 1993, São Paulo (Vila Missionária). Astrofísica e Ciência Política por Harvard (2016). Deputada federal em 2018 (PDT) e 2022 (PSB), com foco em educação; candidata à prefeitura de São Paulo em 2024; reeleita em 2026 com 476 mil votos.",
 "Why here: the centre-left's new generation, inside the Lula coalition but with its own agenda.",
 "Por que aqui: a nova geração da centro-esquerda, dentro da coalizão de Lula mas com agenda própria."),
(2022,"left","Luiz Inácio Lula da Silva","PT · SP",
 "Born 1945, Caetés (PE). Lathe operator, SENAI. Convicted in 2017, jailed 580 days, convictions annulled in 2021; elected president for a third term in 2022 with 50.9% against Bolsonaro, with a broad front from PSOL to PSDB; candidate for a fourth term in the 25 October 2026 run-off.",
 "Nascido em 1945, Caetés (PE). Torneiro mecânico pelo SENAI. Condenado em 2017, preso 580 dias, condenações anuladas em 2021; eleito presidente para o terceiro mandato em 2022 com 50,9% contra Bolsonaro, com uma frente ampla do PSOL ao PSDB; candidato ao quarto mandato no segundo turno de 25 de outubro de 2026.",
 "Why here: PT's 68 seats in 2022 came with a president at the head of a front, not a party programme.",
 "Por que aqui: as 68 cadeiras do PT em 2022 vieram com um presidente à frente de uma frente, não de um programa partidário."),
(2022,"far_left","Sâmia Bomfim","PSOL · SP",
 "Born 1989, Marília (SP). Letters, University of São Paulo. Student-movement activist, city councillor in São Paulo 2017–18, elected federal deputy in 2018 and re-elected in 2022 and 2026 (583,000 votes); PSOL leader in the Chamber, known for the party's feminist and anti-austerity agenda.",
 "Nascida em 1989, Marília (SP). Letras pela USP. Militante do movimento estudantil, vereadora de São Paulo 2017–18, eleita deputada federal em 2018 e reeleita em 2022 e 2026 (583 mil votos); líder do PSOL na Câmara, conhecida pela pauta feminista e antiausteridade do partido.",
 "Why here: PSOL's 12 seats in 2022, inside the Lula front but outside its economic consensus.",
 "Por que aqui: as 12 cadeiras do PSOL em 2022, dentro da frente de Lula mas fora de seu consenso econômico."),
# ───────────────────────── 2026 ─────────────────────────
(2026,"far_right","Flávio Bolsonaro","PL · RJ",
 "Born 1981, Resende (RJ). Law degree, Cândido Mendes University. State deputy in Rio 2003–18, senator since 2019, the family's institutional operator in Congress; PL presidential candidate in 2026, first in the 4 October round with 47% against Lula's 45%, facing the 25 October run-off.",
 "Nascido em 1981, Resende (RJ). Bacharel em Direito pela Universidade Cândido Mendes. Deputado estadual no Rio 2003–18, senador desde 2019, o operador institucional da família no Congresso; candidato do PL à Presidência em 2026, primeiro no turno de 4 de outubro com 47% contra 45% de Lula, disputando o segundo turno em 25 de outubro.",
 "Why here: PL's 121 seats in 2026 are the largest single-party bench since 1990.",
 "Por que aqui: as 121 cadeiras do PL em 2026 são a maior bancada de um partido desde 1990."),
(2026,"right","Marcel van Hattem","Novo · RS",
 "Born 1985. International relations, UFRGS; master's in political science, Leiden. Federal deputy since 2019 for Novo, re-elected in 2022 and 2026; Novo rose to 10 seats in 2026, its best result, on an economic-liberal, anti-STF platform.",
 "Nascido em 1985. Relações Internacionais pela UFRGS; mestre em Ciência Política por Leiden. Deputado federal desde 2019 pelo Novo, reeleito em 2022 e 2026; o Novo subiu a 10 cadeiras em 2026, seu melhor resultado, com plataforma liberal na economia e anti-STF.",
 "Why here: the non-Bolsonarist right that votes with PL — Novo, Republicanos, PRD, Missão.",
 "Por que aqui: a direita não bolsonarista que vota com o PL — Novo, Republicanos, PRD, Missão."),
(2026,"centre_right","Ciro Nogueira","PP · PI",
 "Born 1968, Teresina. Law degree, PUC-Rio. Federal deputy 1995–2011, senator since 2011, PP national president, Bolsonaro's Chief of Staff 2021–22 and the broker of the centrão's entry into that government; opposition under Lula. Re-elected senator in 2026.",
 "Nascido em 1968, Teresina. Bacharel em Direito pela PUC-Rio. Deputado federal 1995–2011, senador desde 2011, presidente nacional do PP, ministro da Casa Civil de Bolsonaro 2021–22 e articulador da entrada do centrão naquele governo; oposição sob Lula. Reeleito senador em 2026.",
 "Why here: the PP–União federation (87 seats) is the pivot of the 2026 Chamber — and of any impeachment.",
 "Por que aqui: a federação PP–União (87 cadeiras) é o pivô da Câmara de 2026 — e de qualquer impeachment."),
(2026,"centre","Simone Tebet","MDB · MS",
 "Born 1970, Três Lagoas. Law degree, UFRJ; master's, PUC-SP. Minister of Planning since 2023, the MDB's face in the Lula government while most of its 36 deputies and 8 senators keep their distance; did not run in 2026.",
 "Nascida em 1970, Três Lagoas. Bacharel em Direito pela UFRJ; mestre pela PUC-SP. Ministra do Planejamento desde 2023, o rosto do MDB no governo Lula enquanto a maioria de seus 36 deputados e 8 senadores mantém distância; não concorreu em 2026.",
 "Why here: MDB shrank to 36 seats but remains the swing bloc between the two camps.",
 "Por que aqui: o MDB encolheu para 36 cadeiras, mas segue como bloco de desempate entre os dois campos."),
(2026,"centre_left","João Campos","PSB · PE",
 "Born 1993, Recife. Civil engineer, Federal University of Pernambuco; son of Eduardo Campos. Federal deputy 2019–20, mayor of Recife 2021–26 (re-elected with 78%), PSB national president since 2025, elected governor of Pernambuco in 2026.",
 "Nascido em 1993, Recife. Engenheiro civil pela UFPE; filho de Eduardo Campos. Deputado federal 2019–20, prefeito do Recife 2021–26 (reeleito com 78%), presidente nacional do PSB desde 2025, eleito governador de Pernambuco em 2026.",
 "Why here: PSB's 15 seats make it the largest centre-left bench; Pernambuco is its base.",
 "Por que aqui: as 15 cadeiras do PSB fazem dele a maior bancada de centro-esquerda; Pernambuco é sua base."),
(2026,"left","Fernando Haddad","PT · SP",
 "Born 1963, São Paulo. Law, master's in economics and PhD in philosophy, all at USP. Minister of Education 2005–12, mayor of São Paulo 2013–16, presidential candidate in 2018, Minister of Finance since 2023 (fiscal framework, tax reform). PT's likely successor figure.",
 "Nascido em 1963, São Paulo. Direito, mestrado em Economia e doutorado em Filosofia, todos pela USP. Ministro da Educação 2005–12, prefeito de São Paulo 2013–16, candidato à Presidência em 2018, ministro da Fazenda desde 2023 (arcabouço fiscal, reforma tributária). Provável sucessor no PT.",
 "Why here: PT's 70 seats in 2026 — stable, and the party's academic-technocratic wing in charge of the economy.",
 "Por que aqui: as 70 cadeiras do PT em 2026 — estáveis, e a ala acadêmico-tecnocrática do partido no comando da economia."),
(2026,"far_left","Erika Hilton","PSOL · SP",
 "Born 1992, Franco da Rocha (SP). Studied gerontology at the Federal University of São Carlos; Black trans activist. City councillor in São Paulo in 2020 (most voted woman in the country), federal deputy in 2022 and re-elected in 2026 with 1.6 million votes, the third-largest tally in Brazil.",
 "Nascida em 1992, Franco da Rocha (SP). Cursou Gerontologia na UFSCar; ativista negra e trans. Vereadora de São Paulo em 2020 (mulher mais votada do país), deputada federal em 2022 e reeleita em 2026 com 1,6 milhão de votos, a terceira maior votação do Brasil.",
 "Why here: PSOL's 14 seats in 2026 are its record; its vote is urban, young and concentrated in São Paulo.",
 "Por que aqui: as 14 cadeiras do PSOL em 2026 são seu recorde; seu voto é urbano, jovem e concentrado em São Paulo."),
]

# Source page used for each biography. Pages I fetched and checked during assembly are listed
# explicitly; the rest point to the Portuguese Wikipedia entry, which is the reference I drew on.
W = "https://pt.wikipedia.org/wiki/"
SOURCES = {
 "Enéas Carneiro": W+"Enéas_Carneiro",
 "Luís Eduardo Magalhães": W+"Luís_Eduardo_Magalhães",
 "Álvaro Valle": W+"Álvaro_Valle",
 "Ibsen Pinheiro": W+"Ibsen_Pinheiro",
 "Miguel Arraes": W+"Miguel_Arraes",
 "Luiz Inácio Lula da Silva": W+"Luiz_Inácio_Lula_da_Silva",
 "Roberto Freire": W+"Roberto_Freire",
 "Jair Bolsonaro": W+"Jair_Bolsonaro",
 "Antônio Carlos Magalhães": W+"Antônio_Carlos_Magalhães",
 "Fernando Henrique Cardoso": W+"Fernando_Henrique_Cardoso",
 "Itamar Franco": W+"Itamar_Franco",
 "Leonel Brizola": W+"Leonel_Brizola",
 "Marta Suplicy": W+"Marta_Suplicy",
 "José Maria de Almeida": W+"José_Maria_de_Almeida",
 "Inocêncio Oliveira": W+"Inocêncio_Oliveira",
 "Mário Covas": W+"Mário_Covas",
 "Jader Barbalho": W+"Jader_Barbalho",
 "Ciro Gomes": W+"Ciro_Gomes",
 "Aloizio Mercadante": W+"Aloizio_Mercadante",
 "Rui Costa Pimenta": W+"Rui_Costa_Pimenta",
 "Delfim Netto": W+"Delfim_Netto",
 "José Serra": W+"José_Serra",
 "José Sarney": W+"José_Sarney",
 "Eduardo Campos": W+"Eduardo_Campos",
 "Luciana Genro": "https://en.wikipedia.org/wiki/Luciana_Genro",
 "Paulo Maluf": W+"Paulo_Maluf",
 "Geraldo Alckmin": W+"Geraldo_Alckmin",
 "Renan Calheiros": W+"Renan_Calheiros",
 "Jaques Wagner": W+"Jaques_Wagner",
 "Heloísa Helena": W+"Heloísa_Helena",
 "Marco Feliciano": W+"Marco_Feliciano",
 "Aécio Neves": W+"Aécio_Neves",
 "Michel Temer": W+"Michel_Temer",
 "Dilma Rousseff": W+"Dilma_Rousseff",
 "Plínio de Arruda Sampaio": W+"Plínio_de_Arruda_Sampaio",
 "Eduardo Bolsonaro": "https://www.brasilparalelo.com.br/noticias/quem-e-eduardo-bolsonaro-a-trajetoria-do-deputado-que-se-tornou-alvo-de-investigacao-pela-suprema-corte",
 "Rodrigo Maia": W+"Rodrigo_Maia",
 "Gilberto Kassab": W+"Gilberto_Kassab",
 "Eduardo Cunha": W+"Eduardo_Cunha",
 "Marina Silva": W+"Marina_Silva",
 "Rui Costa": W+"Rui_Costa",
 "Chico Alencar": W+"Chico_Alencar",
 "Marcel van Hattem": "https://www.marcelvanhattem.com.br/press-kit/",
 "João Doria": W+"João_Doria",
 "Henrique Meirelles": W+"Henrique_Meirelles",
 "Gleisi Hoffmann": W+"Gleisi_Hoffmann",
 "Guilherme Boulos": "https://www.poder360.com.br/poder-governo/saiba-quem-e-guilherme-boulos-novo-ministro-da-secretaria-geral/",
 "Nikolas Ferreira": "https://querobolsa.com.br/revista/nikolas-ferreira-e-formado-em-que",
 "Hugo Motta": "https://www.opovo.com.br/noticias/politica/2025/02/01/hugo-motta-conheca-o-novo-presidente-da-camara-dos-deputados.html",
 "Arthur Lira": "https://www.infomoney.com.br/?p=2237868",
 "Simone Tebet": W+"Simone_Tebet",
 "Tabata Amaral": W+"Tabata_Amaral",
 "Sâmia Bomfim": W+"Sâmia_Bomfim",
 "Flávio Bolsonaro": W+"Flávio_Bolsonaro",
 "Ciro Nogueira": "https://www25.senado.leg.br/web/senadores/senador/-/perfil/739",
 "João Campos": W+"João_Campos_(político)",
 "Fernando Haddad": W+"Fernando_Haddad",
 "Erika Hilton": W+"Erika_Hilton",
}

# Additional 2026 Pernambuco deputies requested for the left and far-left bins.
P += [
(2026,"left","Rosa Amorim","PT · PE",
 "Born around 2000; raised in the Normandia settlement of the Landless Workers' Movement (MST) in Caruaru (PE). Theatre degree, Federal University of Pernambuco; activist in Levante Popular da Juventude and the UNE. State deputy for Pernambuco from 2023, elected federal deputy in 2026 with 144,000 votes — the first MST woman in the Chamber.",
 "Nascida por volta de 2000; criada no Assentamento Normandia, do MST, em Caruaru (PE). Formada em Teatro pela UFPE; militante do Levante Popular da Juventude e da UNE. Deputada estadual por Pernambuco desde 2023, eleita deputada federal em 2026 com 144 mil votos — a primeira mulher do MST na Câmara.",
 "Why here: PT's social-movement wing — the MST base that the party's governing years never fully absorbed.",
 "Por que aqui: a ala de movimentos sociais do PT — a base do MST que os anos de governo do partido nunca absorveram por completo."),
(2026,"far_left","Jones Manoel","PSOL (PCBR) · PE",
 "Born around 1990 in the Borborema favela, Recife. Historian, Federal University of Pernambuco; taught at a popular pre-university course. Became a national figure through his YouTube channel on Marxist theory and Brazilian history. Member of the unregistered PCBR, elected federal deputy in 2026 on the PSOL ticket with 249,000 votes, the second most voted in Pernambuco.",
 "Nascido por volta de 1990 na favela da Borborema, Recife. Historiador pela UFPE; professor de cursinho popular. Tornou-se figura nacional por seu canal no YouTube sobre teoria marxista e história do Brasil. Militante do PCBR, sem registro eleitoral, eleito deputado federal em 2026 pela legenda do PSOL com 249 mil votos, o segundo mais votado de Pernambuco.",
 "Why here: the communist current that runs inside PSOL's federation — the first self-declared communist deputy from Pernambuco since Roberto Freire in 1986.",
 "Por que aqui: a corrente comunista que corre dentro da federação do PSOL — o primeiro deputado comunista declarado de Pernambuco desde Roberto Freire em 1986."),
]
SOURCES.update({
 "Rosa Amorim": "https://www.brasildefato.com.br/2026/10/06/quem-e-rosa-amorim-primeira-mulher-do-mst-eleita-deputada-federal/",
 "Jones Manoel": "https://diplomatique.org.br/jones-manoel-e-a-esperanca-da-revolucao-brasileira/",
})

# Pernambuco figures requested.
P += [
(1998,"centre","Jarbas Vasconcelos","PMDB · PE",
 "Born 1942, Vicência (PE). Law degree, Catholic University of Pernambuco. Co founder of the MDB in 1966, state deputy in 1970, federal deputy in 1974 (most voted in the state) and 1982, mayor of Recife 1986 to 1989 and 1993 to 1997, elected governor of Pernambuco in 1998 and re elected in 2002, senator 2007 to 2015 and 2019 to 2023.",
 "Nascido em 1942, Vicência (PE). Bacharel em Direito pela Universidade Católica de Pernambuco. Cofundador do MDB em 1966, deputado estadual em 1970, deputado federal em 1974 (o mais votado do estado) e 1982, prefeito do Recife 1986 a 1989 e 1993 a 1997, eleito governador de Pernambuco em 1998 e reeleito em 2002, senador 2007 a 2015 e 2019 a 2023.",
 "Why here: a founder of the MDB who governed Pernambuco in coalition with the PFL and PSDB, the state version of the party's national role.",
 "Por que aqui: um fundador do MDB que governou Pernambuco em coalizão com PFL e PSDB, a versão estadual do papel nacional do partido."),
(2010,"left","João Paulo Lima e Silva","PT · PE",
 "Born 1952, Olinda. Metalworker and union activist; later an economics degree from Faculdade Boa Viagem. City councillor in Recife (1988), state deputy 1991 to 2000, mayor of Recife 2001 to 2008 (two terms, the PT's showcase city in the Northeast), elected federal deputy in 2010, state deputy again in 2018.",
 "Nascido em 1952, Olinda. Metalúrgico e sindicalista; depois economista pela Faculdade Boa Viagem. Vereador do Recife (1988), deputado estadual 1991 a 2000, prefeito do Recife 2001 a 2008 (dois mandatos, a cidade vitrine do PT no Nordeste), eleito deputado federal em 2010, deputado estadual de novo em 2018.",
 "Why here: the union origin PT that built the party's first big city administrations in the Northeast.",
 "Por que aqui: o PT de origem sindical que construiu as primeiras grandes administrações municipais do partido no Nordeste."),
(2010,"centre_left","João Lyra Neto","PDT · PE",
 "Born 1947, Caruaru. Law degree, Recife Law School; businessman in the family transport group. Mayor of Caruaru 1989 to 1993 and 1997 to 2000, state deputy, vice governor of Pernambuco 2007 to 2014 on Eduardo Campos's ticket (elected 2006 and 2010), governor in 2014 after Campos resigned to run for president. Later PSD. Father of Raquel Lyra.",
 "Nascido em 1947, Caruaru. Bacharel pela Faculdade de Direito do Recife; empresário do grupo de transportes da família. Prefeito de Caruaru 1989 a 1993 e 1997 a 2000, deputado estadual, vice governador de Pernambuco 2007 a 2014 na chapa de Eduardo Campos (eleito em 2006 e 2010), governador em 2014 após a renúncia de Campos para disputar a Presidência. Depois PSD. Pai de Raquel Lyra.",
 "Why here: the PDT as junior partner of the PSB coalition that ran Pernambuco from 2007 to 2022.",
 "Por que aqui: o PDT como sócio menor da coalizão do PSB que governou Pernambuco de 2007 a 2022."),
(2022,"centre_right","Raquel Lyra","PSDB → PSD · PE",
 "Born 1978, Recife. Law degree, Federal University of Pernambuco; postgraduate in business law, FGV. Federal police chief and state attorney general. State deputy 2011 to 2016 (PSB), mayor of Caruaru 2017 to 2022 (PSDB), elected governor of Pernambuco in 2022, the first woman in the office; moved to PSD in 2025 and was re elected in 2026.",
 "Nascida em 1978, Recife. Bacharel em Direito pela UFPE; pós graduação em Direito Empresarial pela FGV. Delegada da Polícia Federal e procuradora geral do estado. Deputada estadual 2011 a 2016 (PSB), prefeita de Caruaru 2017 a 2022 (PSDB), eleita governadora de Pernambuco em 2022, a primeira mulher no cargo; migrou para o PSD em 2025 e foi reeleita em 2026.",
 "Why here: the centre right that beat the PSB machine in Pernambuco, then moved from PSDB to PSD as the former shrank.",
 "Por que aqui: a centro direita que derrotou a máquina do PSB em Pernambuco e depois migrou do PSDB para o PSD conforme o primeiro encolhia."),
]
SOURCES.update({
 "Jarbas Vasconcelos": W+"Jarbas_Vasconcelos",
 "João Paulo Lima e Silva": W+"João_Paulo_Lima_e_Silva",
 "João Lyra Neto": W+"João_Lyra_Neto",
 "Raquel Lyra": W+"Raquel_Lyra",
})
